name: Check Changelog

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.pull_request.title, 'Revert')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test Bazel
        run: bazel --version

      - name: Cat File Tree
        run: tree

      - name: Cat Git Log
        run: git log --pretty=oneline

      - name: Cat Git status
        run: |
          echo "GITHUB API URL: $GITHUB_API_URL"
          echo "GITHUB SERVER URL: $GITHUB_SERVER_URL"
          echo "Repository Path: ${{ github.repository }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

      # - name: Cat Git full status
      #   run: echo "github: ${{ github }}"

      - name: Run Python script
        env:
          BASH_COMMIT_ID: ${{ github.event.pull_request.base.sha }}
          PR_COMMIT_ID: ${{ github.sha }}
        run: |
          echo "${{ github.event.before }}"
          echo "${{ github.sha }}"
          echo "=================Run Python script begin=============="
          CI_DEBUG=on bazel run //scripts:check_changelog -- \
            --workspace ${{ github.workspace }} \
            --api-url "$GITHUB_API_URL" \
            --repo-path "$GITHUB_SERVER_URL" \
            --pr-number ${{ github.event.pull_request.number }} \
            --base-commit-id ${{ github.event.pull_request.base.sha }} \
            --pr-commit-id ${{ github.sha }}
          echo "=================Run Python script end==============="
