name: Pull Request Check Changelog

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.pull_request.title, 'Revert')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test Bazel
        run: bazel --version

      - name: Cat File Tree
        run: tree

      - name: Cat Git Log
        run: git log --pretty=oneline

      - name: Run Python script
        env:
          BASH_COMMIT_ID: ${{ github.event.pull_request.base.sha }}
          PR_COMMIT_ID: ${{ github.event.pull_request.head.sha }}
        run: |
          echo "=================Run Python script begin=============="
          CI_DEBUG=on bazel run //scripts:check_changelog -- \
            --base-commit-id "$BASH_COMMIT_ID" \
            --pr-commit-id "$PR_COMMIT_ID"
          echo "=================Run Python script end==============="
