name: Pull Request Check Changelog

on:
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        id: list_files
        run: |
          git diff --name-status origin/main..origin/feature_action_test
