name: Pull Request Check Changelog

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch branches
        run: git fetch origin

      - name: List changed files
        id: list_files
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory: $(ls -a)"
          git diff --name-status origin/main..origin/feature_action_test > changed_files.txt
          echo "FILES_PATH=changed_files.txt" >> $GITHUB_ENV

      - name: Run Python script
        run: python ./scripts/check_changelog.py
        env:
          CHANGED_FILES: ${{ env.FILES_PATH }}
