name: Pull Request Check Changelog

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python ./scripts/check_revert.py
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Check if it's a PR revert
        id: check_pr_revert
        run: |
          echo "=========================="
          echo "${{ github.event.pull_request.merged }}"
          echo "${{ github.event.pull_request.merged_by }}"
          echo "=========================="
          if [[ -n "${{ github.event.pull_request.merged }}" && -n "${{ github.event.pull_request.merged_by }}" ]]; then
            echo "PR Revert detected"
          else
            echo "Not a PR Revert"
          fi
      

      - name: Check PR or PR revert
        run: |
          PR_NUMBER=$(echo "${GITHUB_REF}" | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "=========================="
          echo "${GITHUB_REF}"
          echo "${PR_NUMBER}"
          echo "=========================="

          # Fetch the PR details using GitHub REST API
          PR_DETAILS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}")
          echo "===========PR_DETAILS==============="
          echo "${PR_DETAILS}"
          echo "===========PR_DETAILS==============="

          # Check if the PR has a 'reverted' label
          if echo "${PR_DETAILS}" | jq '.labels[].name' | grep -q 'reverted'; then
            echo "This is a PR revert"
            # Your PR revert specific steps here
          else
            echo "This is a regular PR"
            # Your regular PR steps here
          fi

      - name: List changed files
        id: list_files
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory: $(ls -a)"
          echo "=========github.event.before============"
          echo "${{ github.event.before }}"
          echo "=========github.sha============"
          echo "${{ github.sha }}"
          echo "=========github.event.pull_request.base.sha============"
          echo "${{ github.event.pull_request.base.sha }}"
          echo "diff content"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          echo "FILES_PATH=changed_files.txt" >> $GITHUB_ENV

      - name: Run Python script
        run: python ./scripts/check_changelog.py
        env:
          CHANGED_FILES: ${{ env.FILES_PATH }}
