name: Pull Request Check Changelog

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python ./scripts/check_revert.py
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}      

      - name: List changed files
        id: list_files
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the current directory: $(ls -a)"
          echo "=========github.event.before============"
          echo "${{ github.event.before }}"
          echo "=========github.sha============"
          echo "${{ github.sha }}"
          echo "=========github.event.pull_request.base.sha============"
          echo "${{ github.event.pull_request.base.sha }}"
          echo "=========github.event.pull_request.head.sha============"
          echo "${{ github.event.pull_request.head.sha }}"
          echo "diff content begin"
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
          echo "diff content end"
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > changed_files.txt
          echo "FILES_PATH=changed_files.txt" >> $GITHUB_ENV

      - name: Run Python script
        run: python ./scripts/check_changelog.py
        env:
          CHANGED_FILES: ${{ env.FILES_PATH }}
