name: Pull Request Check Changelog

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*'
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.pull_request.title, 'Revert')"
    steps:
      - name: Check revert
        run: echo "this is a Revert action"
        id: check_revert
        if: '!startsWith(github.event.pull_request.title, ''Revert'')'

      - name: Check run
        run: echo "=======check run step"
        if: steps.check_revert.outputs.result == 'true'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Python script
        run: python ./scripts/check_revert.py
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}

      - name: Run Python script
        run: python ./scripts/check_changelog.py
        env:
          BASH_COMMIT_ID: ${{ github.event.pull_request.base.sha }}
          PR_COMMIT_ID: ${{ github.event.pull_request.head.sha }}
