name: Pull Request Check Changelog

on:
  workflow_dispatch:

jobs:
  list_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        id: list_files
        run: |
          echo "::set-output name=files::$(git diff --name-status main..feature_action_test)"

      - name: Run Python script
        run: python ./scripts/check_changelog.py
        env:
          CHANGED_FILES: ${{ steps.list_files.outputs.files }}
