name: Pull Request Check Changelog

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  list_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List changed files
        run: |
          echo "Changed Files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
